<?php

return [
    'categories' => [
        ['id' => 1, 'name' => 'Monitor', 'description' => 'Monitor komputer dan display'],
        ['id' => 2, 'name' => 'Laptop', 'description' => 'Laptop dan notebook komputer'],
        ['id' => 3, 'name' => 'Keyboard', 'description' => 'Keyboard dan input devices'],
        ['id' => 4, 'name' => 'Mouse', 'description' => 'Mouse dan pointing devices'],
        ['id' => 5, 'name' => 'Headset', 'description' => 'Headset dan audio devices'],
        ['id' => 6, 'name' => 'Printer', 'description' => 'Printer dan mesin print'],
        ['id' => 7, 'name' => 'Scanner', 'description' => 'Scanner dan perangkat scanning'],
    ],

    'suppliers' => [
        ['id' => 1, 'name' => 'PT. Monitor Technik', 'contact' => '081234567890', 'address' => 'Jl. Elektronik No. 123, Jakarta'],
        ['id' => 2, 'name' => 'CV. Laptop Center', 'contact' => '082345678901', 'address' => 'Jl. Komputer No. 456, Bandung'],
        ['id' => 3, 'name' => 'UD. Keyboard Pro', 'contact' => '083456789012', 'address' => 'Jl. Input No. 789, Surabaya'],
        ['id' => 4, 'name' => 'PT. Mouse Devices', 'contact' => '084567890123', 'address' => 'Jl. Pointing No. 321, Medan'],
        ['id' => 5, 'name' => 'Toko Headset Premium', 'contact' => '085678901234', 'address' => 'Jl. Audio No. 654, Yogyakarta'],
        ['id' => 6, 'name' => 'PT. Printer Solutions', 'contact' => '086789012345', 'address' => 'Jl. Print No. 987, Makassar'],
    ],

    'products' => [
        // Monitor Category (1)
        [
            'id' => 1,
            'name' => 'Monitor LED 24" Full HD',
            'code' => 'MONITOR-001',
            'category_id' => 1,
            'category_name' => 'Monitor',
            'supplier_id' => 1,
            'supplier_name' => 'PT. Monitor Technik',
            'price' => 2150000,
            'stock' => 28,
            'unit' => 'pcs',
            'description' => 'Monitor LED dengan resolusi Full HD (1920x1080) dan panel IPS berkualitas tinggi, sempurna untuk office dan graphic design',
            'image' => 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 08:30:00',
        ],
        [
            'id' => 2,
            'name' => 'Monitor Curved 27" 144Hz',
            'code' => 'MONITOR-002',
            'category_id' => 1,
            'category_name' => 'Monitor',
            'supplier_id' => 1,
            'supplier_name' => 'PT. Monitor Technik',
            'price' => 4250000,
            'stock' => 15,
            'unit' => 'pcs',
            'description' => 'Monitor curved premium dengan refresh rate 144Hz dan response time 1ms, ideal untuk gaming profesional',
            'image' => 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 09:15:00',
        ],
        [
            'id' => 3,
            'name' => 'Monitor Ultra Wide 34" 3440x1440',
            'code' => 'MONITOR-003',
            'category_id' => 1,
            'category_name' => 'Monitor',
            'supplier_id' => 1,
            'supplier_name' => 'PT. Monitor Technik',
            'price' => 5850000,
            'stock' => 8,
            'unit' => 'pcs',
            'description' => 'Monitor ultra wide untuk multi-tasking dan professional workflows dengan curved IPS panel',
            'image' => 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 10:00:00',
        ],
        // Laptop Category (2)
        [
            'id' => 4,
            'name' => 'Laptop Gaming Pro 15" RTX 4070',
            'code' => 'LAPTOP-001',
            'category_id' => 2,
            'category_name' => 'Laptop',
            'supplier_id' => 2,
            'supplier_name' => 'CV. Laptop Center',
            'price' => 18500000,
            'stock' => 12,
            'unit' => 'pcs',
            'description' => 'Laptop gaming kelas atas dengan Intel i9-13900H, RTX 4070, 16GB DDR5, dan SSD 1TB NVMe untuk performa maksimal',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 11:20:00',
        ],
        [
            'id' => 5,
            'name' => 'Laptop Ultrabook 13" i7-1360P',
            'code' => 'LAPTOP-002',
            'category_id' => 2,
            'category_name' => 'Laptop',
            'supplier_id' => 2,
            'supplier_name' => 'CV. Laptop Center',
            'price' => 12500000,
            'stock' => 20,
            'unit' => 'pcs',
            'description' => 'Laptop ultrabook sangat ringan (1.1kg) dengan Intel i7 gen terbaru, cocok untuk profesional mobile dengan baterai 14+ jam',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 12:45:00',
        ],
        [
            'id' => 6,
            'name' => 'Laptop Business 14" i5-1340P',
            'code' => 'LAPTOP-003',
            'category_id' => 2,
            'category_name' => 'Laptop',
            'supplier_id' => 2,
            'supplier_name' => 'CV. Laptop Center',
            'price' => 8950000,
            'stock' => 25,
            'unit' => 'pcs',
            'description' => 'Laptop business dengan Intel i5, memori 8GB, SSD 512GB, dan baterai tahan lama - perfect untuk pekerjaan kantoran',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 08:30:00',
        ],
        // Keyboard Category (3)
        [
            'id' => 7,
            'name' => 'Keyboard Mechanical RGB Hot-swap',
            'code' => 'KEYBOARD-001',
            'category_id' => 3,
            'category_name' => 'Keyboard',
            'supplier_id' => 3,
            'supplier_name' => 'UD. Keyboard Pro',
            'price' => 1250000,
            'stock' => 45,
            'unit' => 'pcs',
            'description' => 'Keyboard mechanical gaming dengan RGB backlight, hot-swap switches, dan aluminum frame - sangat responsif dan tahan lama',
            'image' => 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 13:00:00',
        ],
        [
            'id' => 8,
            'name' => 'Keyboard Wireless Compact Slimline',
            'code' => 'KEYBOARD-002',
            'category_id' => 3,
            'category_name' => 'Keyboard',
            'supplier_id' => 3,
            'supplier_name' => 'UD. Keyboard Pro',
            'price' => 650000,
            'stock' => 60,
            'unit' => 'pcs',
            'description' => 'Keyboard wireless ringkas dengan baterai tahan lama 30 hari, design minimalis cocok untuk mobile workers',
            'image' => 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 14:00:00',
        ],
        [
            'id' => 9,
            'name' => 'Keyboard Ergonomic Wireless',
            'code' => 'KEYBOARD-003',
            'category_id' => 3,
            'category_name' => 'Keyboard',
            'supplier_id' => 3,
            'supplier_name' => 'UD. Keyboard Pro',
            'price' => 890000,
            'stock' => 35,
            'unit' => 'pcs',
            'description' => 'Keyboard ergonomic dengan design curved, cocok untuk user yang bekerja 8+ jam sehari dengan comfort maksimal',
            'image' => 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 09:00:00',
        ],
        // Mouse Category (4)
        [
            'id' => 10,
            'name' => 'Mouse Wireless Pro 2.4GHz',
            'code' => 'MOUSE-001',
            'category_id' => 4,
            'category_name' => 'Mouse',
            'supplier_id' => 4,
            'supplier_name' => 'PT. Mouse Devices',
            'price' => 650000,
            'stock' => 87,
            'unit' => 'pcs',
            'description' => 'Mouse wireless dengan sensor optik presisi 2400DPI, cocok untuk office dan light gaming dengan jarak 10m',
            'image' => 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 15:00:00',
        ],
        [
            'id' => 11,
            'name' => 'Mouse Gaming RGB 8 Button Programmable',
            'code' => 'MOUSE-002',
            'category_id' => 4,
            'category_name' => 'Mouse',
            'supplier_id' => 4,
            'supplier_name' => 'PT. Mouse Devices',
            'price' => 950000,
            'stock' => 52,
            'unit' => 'pcs',
            'description' => 'Mouse gaming dengan 8 tombol programmable, sensor DPI hingga 12800, RGB lighting, cocok untuk competitive gaming',
            'image' => 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 16:00:00',
        ],
        [
            'id' => 12,
            'name' => 'Mouse Vertical Ergonomic',
            'code' => 'MOUSE-003',
            'category_id' => 4,
            'category_name' => 'Mouse',
            'supplier_id' => 4,
            'supplier_name' => 'PT. Mouse Devices',
            'price' => 750000,
            'stock' => 42,
            'unit' => 'pcs',
            'description' => 'Mouse vertical ergonomic untuk mencegah carpal tunnel, cocok untuk office workers yang menggunakan mouse 8+ jam',
            'image' => 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 10:00:00',
        ],
        // Headset Category (5)
        [
            'id' => 13,
            'name' => 'Headset Gaming Stereo 7.1',
            'code' => 'HEADSET-001',
            'category_id' => 5,
            'category_name' => 'Headset',
            'supplier_id' => 5,
            'supplier_name' => 'Toko Headset Premium',
            'price' => 950000,
            'stock' => 18,
            'unit' => 'pcs',
            'description' => 'Headset gaming dengan audio surround 7.1, microphone noise cancelling, dan cushion empuk untuk sesi gaming marathon',
            'image' => 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 17:00:00',
        ],
        [
            'id' => 14,
            'name' => 'Headset Wireless Premium ANC',
            'code' => 'HEADSET-002',
            'category_id' => 5,
            'category_name' => 'Headset',
            'supplier_id' => 5,
            'supplier_name' => 'Toko Headset Premium',
            'price' => 2250000,
            'stock' => 12,
            'unit' => 'pcs',
            'description' => 'Headset wireless premium dengan Active Noise Cancellation, driver audio 40mm Hi-Fi, baterai 30 jam, sempurna untuk travel',
            'image' => 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 18:00:00',
        ],
        [
            'id' => 15,
            'name' => 'Headset USB-C Studio',
            'code' => 'HEADSET-003',
            'category_id' => 5,
            'category_name' => 'Headset',
            'supplier_id' => 5,
            'supplier_name' => 'Toko Headset Premium',
            'price' => 1850000,
            'stock' => 9,
            'unit' => 'pcs',
            'description' => 'Headset studio grade dengan konektivitas USB-C, driver premium 50mm, frequency response 20Hz-20kHz, untuk content creator',
            'image' => 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 11:00:00',
        ],
        // Printer Category (6)
        [
            'id' => 16,
            'name' => 'Printer Laser Monochrome A4',
            'code' => 'PRINTER-001',
            'category_id' => 6,
            'category_name' => 'Printer',
            'supplier_id' => 6,
            'supplier_name' => 'PT. Printer Solutions',
            'price' => 2500000,
            'stock' => 14,
            'unit' => 'pcs',
            'description' => 'Printer laser monochrome cepat dengan print speed 35ppm, cocok untuk office dengan volume print tinggi',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-10 19:00:00',
        ],
        [
            'id' => 17,
            'name' => 'Printer Inkjet Color All-in-One',
            'code' => 'PRINTER-002',
            'category_id' => 6,
            'category_name' => 'Printer',
            'supplier_id' => 6,
            'supplier_name' => 'PT. Printer Solutions',
            'price' => 1800000,
            'stock' => 22,
            'unit' => 'pcs',
            'description' => 'Printer inkjet all-in-one (print, scan, copy) dengan color quality tinggi, perfect untuk home office dan SOHO',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
            'created_at' => '2025-01-11 12:00:00',
        ],
    ],

    'inventory_ins' => [
        ['id' => 1, 'product_id' => 1, 'product_name' => 'Monitor LED 24" Full HD', 'quantity' => 20, 'date' => '2025-01-02', 'notes' => 'Stok awal januari', 'supplier' => 'PT. Monitor Technik'],
        ['id' => 2, 'product_id' => 2, 'product_name' => 'Monitor Curved 27" 144Hz', 'quantity' => 10, 'date' => '2025-01-05', 'notes' => 'Restok monitor gaming', 'supplier' => 'PT. Monitor Technik'],
        ['id' => 3, 'product_id' => 3, 'product_name' => 'Monitor Ultra Wide 34"', 'quantity' => 5, 'date' => '2025-01-08', 'notes' => 'Monitor ultra wide batch pertama', 'supplier' => 'PT. Monitor Technik'],
        ['id' => 4, 'product_id' => 4, 'product_name' => 'Laptop Gaming Pro 15" RTX 4070', 'quantity' => 8, 'date' => '2025-01-03', 'notes' => 'Pengiriman laptop gaming', 'supplier' => 'CV. Laptop Center'],
        ['id' => 5, 'product_id' => 5, 'product_name' => 'Laptop Ultrabook 13" i7-1360P', 'quantity' => 15, 'date' => '2025-01-06', 'notes' => 'Batch ultrabook January', 'supplier' => 'CV. Laptop Center'],
        ['id' => 6, 'product_id' => 6, 'product_name' => 'Laptop Business 14" i5-1340P', 'quantity' => 12, 'date' => '2025-01-09', 'notes' => 'Laptop business edition', 'supplier' => 'CV. Laptop Center'],
        ['id' => 7, 'product_id' => 7, 'product_name' => 'Keyboard Mechanical RGB Hot-swap', 'quantity' => 30, 'date' => '2025-01-04', 'notes' => 'Keyboard gaming mechanical', 'supplier' => 'UD. Keyboard Pro'],
        ['id' => 8, 'product_id' => 8, 'product_name' => 'Keyboard Wireless Compact Slimline', 'quantity' => 40, 'date' => '2025-01-07', 'notes' => 'Keyboard wireless compact', 'supplier' => 'UD. Keyboard Pro'],
        ['id' => 9, 'product_id' => 9, 'product_name' => 'Keyboard Ergonomic Wireless', 'quantity' => 25, 'date' => '2025-01-10', 'notes' => 'Keyboard ergonomic batch', 'supplier' => 'UD. Keyboard Pro'],
        ['id' => 10, 'product_id' => 10, 'product_name' => 'Mouse Wireless Pro 2.4GHz', 'quantity' => 50, 'date' => '2025-01-02', 'notes' => 'Mouse wireless office', 'supplier' => 'PT. Mouse Devices'],
        ['id' => 11, 'product_id' => 11, 'product_name' => 'Mouse Gaming RGB 8 Button', 'quantity' => 35, 'date' => '2025-01-05', 'notes' => 'Mouse gaming RGB batch', 'supplier' => 'PT. Mouse Devices'],
        ['id' => 12, 'product_id' => 12, 'product_name' => 'Mouse Vertical Ergonomic', 'quantity' => 30, 'date' => '2025-01-08', 'notes' => 'Mouse ergonomic vertical', 'supplier' => 'PT. Mouse Devices'],
        ['id' => 13, 'product_id' => 13, 'product_name' => 'Headset Gaming Stereo 7.1', 'quantity' => 15, 'date' => '2025-01-03', 'notes' => 'Headset gaming 7.1', 'supplier' => 'Toko Headset Premium'],
        ['id' => 14, 'product_id' => 14, 'product_name' => 'Headset Wireless Premium ANC', 'quantity' => 10, 'date' => '2025-01-06', 'notes' => 'Headset premium wireless', 'supplier' => 'Toko Headset Premium'],
        ['id' => 15, 'product_id' => 15, 'product_name' => 'Headset USB-C Studio', 'quantity' => 8, 'date' => '2025-01-09', 'notes' => 'Headset studio grade', 'supplier' => 'Toko Headset Premium'],
        ['id' => 16, 'product_id' => 16, 'product_name' => 'Printer Laser Monochrome A4', 'quantity' => 10, 'date' => '2025-01-04', 'notes' => 'Printer laser office', 'supplier' => 'PT. Printer Solutions'],
        ['id' => 17, 'product_id' => 17, 'product_name' => 'Printer Inkjet Color All-in-One', 'quantity' => 18, 'date' => '2025-01-07', 'notes' => 'Printer inkjet all-in-one', 'supplier' => 'PT. Printer Solutions'],
    ],

    'inventory_outs' => [
        ['id' => 1, 'product_id' => 1, 'product_name' => 'Monitor LED 24" Full HD', 'quantity' => 5, 'date' => '2025-01-15', 'description' => 'Penjualan ke PT ABC', 'user' => 'Demo Staf'],
        ['id' => 2, 'product_id' => 4, 'product_name' => 'Laptop Gaming Pro 15" RTX 4070', 'quantity' => 2, 'date' => '2025-01-16', 'description' => 'Order dari toko retail Jakarta', 'user' => 'Demo Staf'],
        ['id' => 3, 'product_id' => 7, 'product_name' => 'Keyboard Mechanical RGB Hot-swap', 'quantity' => 8, 'date' => '2025-01-17', 'description' => 'Penjualan e-commerce', 'user' => 'Demo Staf'],
        ['id' => 4, 'product_id' => 10, 'product_name' => 'Mouse Wireless Pro 2.4GHz', 'quantity' => 12, 'date' => '2025-01-18', 'description' => 'Pengiriman ke distributor regional', 'user' => 'Demo Staf'],
        ['id' => 5, 'product_id' => 13, 'product_name' => 'Headset Gaming Stereo 7.1', 'quantity' => 6, 'date' => '2025-01-19', 'description' => 'Penjualan retail counter', 'user' => 'Demo Staf'],
        ['id' => 6, 'product_id' => 2, 'product_name' => 'Monitor Curved 27" 144Hz', 'quantity' => 3, 'date' => '2025-01-20', 'description' => 'Order khusus dari kantor pusat', 'user' => 'Demo Staf'],
        ['id' => 7, 'product_id' => 5, 'product_name' => 'Laptop Ultrabook 13" i7-1360P', 'quantity' => 4, 'date' => '2025-01-21', 'description' => 'Penjualan online platform', 'user' => 'Demo Staf'],
        ['id' => 8, 'product_id' => 11, 'product_name' => 'Mouse Gaming RGB 8 Button', 'quantity' => 7, 'date' => '2025-01-22', 'description' => 'Pengiriman ke toko mitra', 'user' => 'Demo Staf'],
        ['id' => 9, 'product_id' => 16, 'product_name' => 'Printer Laser Monochrome A4', 'quantity' => 2, 'date' => '2025-01-23', 'description' => 'Order ke perusahaan B', 'user' => 'Demo Staf'],
        ['id' => 10, 'product_id' => 17, 'product_name' => 'Printer Inkjet Color All-in-One', 'quantity' => 3, 'date' => '2025-01-24', 'description' => 'Penjualan print shop', 'user' => 'Demo Staf'],
    ],

    'users' => [
        [
            'id' => 999,
            'name' => 'Demo Admin',
            'email' => 'admin@demo.com',
            'role' => 'admin',
            'company' => 'Demo Company',
            'is_demo' => true
        ],
        [
            'id' => 998,
            'name' => 'Demo Staf',
            'email' => 'staf@demo.com',
            'role' => 'staf',
            'company' => 'Demo Company',
            'is_demo' => true
        ],
    ],

    'statistics' => [
        'total_products' => 17,
        'total_suppliers' => 6,
        'total_categories' => 7,
        'total_inventory_in' => 17,
        'total_inventory_out' => 10,
        'low_stock_items' => [
            'Monitor Ultra Wide 34" 3440x1440' => 8,
            'Headset Wireless Premium ANC' => 12,
            'Headset USB-C Studio' => 9,
        ],
        'total_value' => 250000000, // Estimated total value
    ],

    'demo_user' => [
        'admin' => [
            'id' => 999,
            'name' => 'Demo Admin',
            'email' => 'admin@demo.com',
            'role' => 'admin',
        ],
        'staf' => [
            'id' => 998,
            'name' => 'Demo Staf',
            'email' => 'staf@demo.com',
            'role' => 'staf',
        ],
    ],

    // === FITUR OPTIONAL #1: AUDIT LOGS ===
    'audit_logs' => [
        [
            'id' => 1,
            'user_id' => 999,
            'user_name' => 'Demo Admin',
            'action' => 'created',
            'entity' => 'Product',
            'entity_id' => 1,
            'entity_name' => 'Monitor LED 24" Full HD',
            'old_values' => null,
            'new_values' => ['name' => 'Monitor LED 24" Full HD', 'price' => 2150000],
            'timestamp' => '2025-01-10 08:30:00',
            'created_at' => '2025-01-10 08:30:00',
        ],
        [
            'id' => 2,
            'user_id' => 999,
            'user_name' => 'Demo Admin',
            'action' => 'updated',
            'entity' => 'Product',
            'entity_id' => 1,
            'entity_name' => 'Monitor LED 24" Full HD',
            'old_values' => ['stock' => 20],
            'new_values' => ['stock' => 28],
            'timestamp' => '2025-01-15 10:00:00',
            'created_at' => '2025-01-15 10:00:00',
        ],
        [
            'id' => 3,
            'user_id' => 998,
            'user_name' => 'Demo Staf',
            'action' => 'created',
            'entity' => 'InventoryIn',
            'entity_id' => 1,
            'entity_name' => 'Monitor LED 24" - Stok Masuk',
            'old_values' => null,
            'new_values' => ['product_id' => 1, 'quantity' => 20],
            'timestamp' => '2025-01-15 11:30:00',
            'created_at' => '2025-01-15 11:30:00',
        ],
        [
            'id' => 4,
            'user_id' => 998,
            'user_name' => 'Demo Staf',
            'action' => 'created',
            'entity' => 'InventoryOut',
            'entity_id' => 1,
            'entity_name' => 'Monitor LED 24" - Stok Keluar',
            'old_values' => null,
            'new_values' => ['product_id' => 1, 'quantity' => 5],
            'timestamp' => '2025-01-15 14:00:00',
            'created_at' => '2025-01-15 14:00:00',
        ],
        [
            'id' => 5,
            'user_id' => 999,
            'user_name' => 'Demo Admin',
            'action' => 'created',
            'entity' => 'User',
            'entity_id' => 1,
            'entity_name' => 'John Doe',
            'old_values' => null,
            'new_values' => ['name' => 'John Doe', 'email' => 'john@demo.com', 'role' => 'staf'],
            'timestamp' => '2025-01-20 09:00:00',
            'created_at' => '2025-01-20 09:00:00',
        ],
        [
            'id' => 6,
            'user_id' => 999,
            'user_name' => 'Demo Admin',
            'action' => 'updated',
            'entity' => 'Category',
            'entity_id' => 1,
            'entity_name' => 'Monitor',
            'old_values' => ['description' => 'Kategori lama'],
            'new_values' => ['description' => 'Monitor komputer dan display'],
            'timestamp' => '2025-01-18 15:30:00',
            'created_at' => '2025-01-18 15:30:00',
        ],
        [
            'id' => 7,
            'user_id' => 999,
            'user_name' => 'Demo Admin',
            'action' => 'deleted',
            'entity' => 'Product',
            'entity_id' => 99,
            'entity_name' => 'Product Terhapus',
            'old_values' => ['id' => 99, 'name' => 'Product Terhapus'],
            'new_values' => null,
            'timestamp' => '2025-01-19 16:00:00',
            'created_at' => '2025-01-19 16:00:00',
        ],
        [
            'id' => 8,
            'user_id' => 998,
            'user_name' => 'Demo Staf',
            'action' => 'viewed',
            'entity' => 'Report',
            'entity_id' => 1,
            'entity_name' => 'Inventory Report',
            'old_values' => null,
            'new_values' => null,
            'timestamp' => '2025-01-22 10:30:00',
            'created_at' => '2025-01-22 10:30:00',
        ],
    ],

    // === FITUR OPTIONAL #2: NOTIFICATIONS ===
    'notifications' => [
        // Notifications for Admin (recipient_id = 999)
        [
            'id' => 1,
            'company_id' => 1,
            'sender_id' => null, // System notification
            'recipient_id' => 999, // Admin
            'template' => 'product_created',
            'message' => 'Produk Monitor LED 24" Full HD telah ditambahkan ke sistem',
            'read_at' => '2025-01-10 08:35:00',
            'created_at' => '2025-01-10 08:30:00',
            'updated_at' => '2025-01-10 08:35:00',
        ],
        [
            'id' => 2,
            'company_id' => 1,
            'sender_id' => 998, // From Staf
            'recipient_id' => 999, // Admin
            'template' => 'inventory_in_created',
            'message' => 'Stok masuk 20 pcs Monitor LED telah berhasil dicatat oleh Demo Staf',
            'read_at' => null,
            'created_at' => '2025-01-22 11:30:00',
            'updated_at' => '2025-01-22 11:30:00',
        ],
        [
            'id' => 3,
            'company_id' => 1,
            'sender_id' => null,
            'recipient_id' => 999,
            'template' => 'low_stock_alert',
            'message' => 'Peringatan: Headset Gaming Stereo memiliki stok hanya 3 unit. Segera lakukan restocking!',
            'read_at' => null,
            'created_at' => '2025-01-22 09:00:00',
            'updated_at' => '2025-01-22 09:00:00',
        ],
        [
            'id' => 4,
            'company_id' => 1,
            'sender_id' => null,
            'recipient_id' => 999,
            'template' => 'user_created',
            'message' => 'User baru "Demo Staf" dengan role staf telah ditambahkan ke sistem',
            'read_at' => '2025-01-20 09:05:00',
            'created_at' => '2025-01-20 09:00:00',
            'updated_at' => '2025-01-20 09:05:00',
        ],
    ],

    // === FITUR OPTIONAL #3: PROFILE MANAGEMENT ===
    'profile_data' => [
        'admin' => [
            'id' => 999,
            'name' => 'Demo Admin',
            'email' => 'admin@demo.com',
            'phone' => '081234567890',
            'company' => 'Demo Company',
            'role' => 'admin',
            'department' => 'Management',
            'address' => 'Jl. Demo No. 123, Jakarta Selatan, 12345',
            'created_at' => '2025-01-01 08:00:00',
            'updated_at' => '2025-01-01 08:00:00',
            'avatar' => 'https://ui-avatars.com/api/?name=Demo+Admin&background=667eea&color=fff',
            'about' => 'Saya adalah admin sistem gudang demo. Bertanggung jawab atas manajemen inventory dan user management.',
            'notifications_enabled' => true,
            'email_notifications' => true,
        ],
        'staf' => [
            'id' => 998,
            'name' => 'Demo Staf',
            'email' => 'staf@demo.com',
            'phone' => '082345678901',
            'company' => 'Demo Company',
            'role' => 'staf',
            'department' => 'Operations',
            'address' => 'Jl. Demo No. 456, Jakarta Timur, 13210',
            'created_at' => '2025-01-01 09:00:00',
            'updated_at' => '2025-01-01 09:00:00',
            'avatar' => 'https://ui-avatars.com/api/?name=Demo+Staf&background=764ba2&color=fff',
            'about' => 'Saya adalah staf operasional yang menangani pencatatan stok masuk dan keluar.',
            'notifications_enabled' => true,
            'email_notifications' => false,
        ],
    ],
];
