<?php

return [
    'categories' => [
        ['id' => 1, 'name' => 'Monitor', 'description' => 'Monitor komputer dan display'],
        ['id' => 2, 'name' => 'Laptop', 'description' => 'Laptop dan notebook'],
        ['id' => 3, 'name' => 'Keyboard', 'description' => 'Keyboard dan input devices'],
        ['id' => 4, 'name' => 'Mouse', 'description' => 'Mouse dan pointing devices'],
        ['id' => 5, 'name' => 'Headset', 'description' => 'Headset dan audio devices'],
    ],

    'suppliers' => [
        ['id' => 1, 'name' => 'PT. Monitor Technik', 'contact' => '081234567890'],
        ['id' => 2, 'name' => 'CV. Laptop Center', 'contact' => '082345678901'],
        ['id' => 3, 'name' => 'UD. Keyboard Pro', 'contact' => '083456789012'],
        ['id' => 4, 'name' => 'PT. Mouse Devices', 'contact' => '084567890123'],
        ['id' => 5, 'name' => 'Toko Headset Premium', 'contact' => '085678901234'],
    ],

    'products' => [
        // Monitor Category (1)
        [
            'id' => 1,
            'name' => 'Monitor LED 24" Full HD',
            'code' => 'MONITOR-001',
            'category_id' => 1,
            'category_name' => 'Monitor',
            'supplier_id' => 1,
            'supplier_name' => 'PT. Monitor Technik',
            'price' => 2150000,
            'stock' => 28,
            'unit' => 'pcs',
            'description' => 'Monitor LED dengan resolusi Full HD dan panel IPS berkualitas tinggi',
            'image' => 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        [
            'id' => 2,
            'name' => 'Monitor Curved 27" 144Hz',
            'code' => 'MONITOR-002',
            'category_id' => 1,
            'category_name' => 'Monitor',
            'supplier_id' => 1,
            'supplier_name' => 'PT. Monitor Technik',
            'price' => 4250000,
            'stock' => 15,
            'unit' => 'pcs',
            'description' => 'Monitor curved dengan refresh rate 144Hz untuk gaming profesional',
            'image' => 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        // Laptop Category (2)
        [
            'id' => 3,
            'name' => 'Laptop Gaming Pro 15"',
            'code' => 'LAPTOP-001',
            'category_id' => 2,
            'category_name' => 'Laptop',
            'supplier_id' => 2,
            'supplier_name' => 'CV. Laptop Center',
            'price' => 18500000,
            'stock' => 12,
            'unit' => 'pcs',
            'description' => 'Laptop gaming dengan spesifikasi tinggi untuk kebutuhan profesional',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
        ],
        [
            'id' => 4,
            'name' => 'Laptop Ultrabook 13" I7',
            'code' => 'LAPTOP-002',
            'category_id' => 2,
            'category_name' => 'Laptop',
            'supplier_id' => 2,
            'supplier_name' => 'CV. Laptop Center',
            'price' => 12500000,
            'stock' => 20,
            'unit' => 'pcs',
            'description' => 'Laptop ultrabook ringan dengan prosesor Intel i7 gen terbaru',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400',
        ],
        // Keyboard Category (3)
        [
            'id' => 5,
            'name' => 'Keyboard Mechanical RGB',
            'code' => 'KEYBOARD-001',
            'category_id' => 3,
            'category_name' => 'Keyboard',
            'supplier_id' => 3,
            'supplier_name' => 'UD. Keyboard Pro',
            'price' => 1250000,
            'stock' => 45,
            'unit' => 'pcs',
            'description' => 'Keyboard mechanical dengan RGB backlight dan switch berkualitas',
            'image' => 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        [
            'id' => 6,
            'name' => 'Keyboard Wireless Compact',
            'code' => 'KEYBOARD-002',
            'category_id' => 3,
            'category_name' => 'Keyboard',
            'supplier_id' => 3,
            'supplier_name' => 'UD. Keyboard Pro',
            'price' => 650000,
            'stock' => 60,
            'unit' => 'pcs',
            'description' => 'Keyboard wireless ringkas dengan baterai tahan lama',
            'image' => 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        // Mouse Category (4)
        [
            'id' => 7,
            'name' => 'Mouse Wireless Pro',
            'code' => 'MOUSE-001',
            'category_id' => 4,
            'category_name' => 'Mouse',
            'supplier_id' => 4,
            'supplier_name' => 'PT. Mouse Devices',
            'price' => 650000,
            'stock' => 87,
            'unit' => 'pcs',
            'description' => 'Mouse wireless dengan teknologi tracking presisi untuk produktivitas maksimal',
            'image' => 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        [
            'id' => 8,
            'name' => 'Mouse Gaming RGB 8 Button',
            'code' => 'MOUSE-002',
            'category_id' => 4,
            'category_name' => 'Mouse',
            'supplier_id' => 4,
            'supplier_name' => 'PT. Mouse Devices',
            'price' => 950000,
            'stock' => 52,
            'unit' => 'pcs',
            'description' => 'Mouse gaming dengan 8 tombol programmable dan sensor DPI tinggi',
            'image' => 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        // Headset Category (5)
        [
            'id' => 9,
            'name' => 'Headset Gaming Stereo',
            'code' => 'HEADSET-001',
            'category_id' => 5,
            'category_name' => 'Headset',
            'supplier_id' => 5,
            'supplier_name' => 'Toko Headset Premium',
            'price' => 950000,
            'stock' => 3,
            'unit' => 'pcs',
            'description' => 'Headset gaming dengan audio surround dan microphone noise cancelling',
            'image' => 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
        [
            'id' => 10,
            'name' => 'Headset Wireless Premium',
            'code' => 'HEADSET-002',
            'category_id' => 5,
            'category_name' => 'Headset',
            'supplier_id' => 5,
            'supplier_name' => 'Toko Headset Premium',
            'price' => 2250000,
            'stock' => 0,
            'unit' => 'pcs',
            'description' => 'Headset wireless premium dengan driver audio 40mm dan noise cancellation aktif',
            'image' => 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=400',
        ],
    ],

    'inventory_ins' => [
        ['id' => 1, 'product_id' => 1, 'product_name' => 'Monitor LED 24" Full HD', 'quantity' => 20, 'date' => '2025-01-15', 'notes' => 'Stok awal bulan'],
        ['id' => 2, 'product_id' => 2, 'product_name' => 'Monitor Curved 27" 144Hz', 'quantity' => 10, 'date' => '2025-01-16', 'notes' => 'Restok dari supplier'],
        ['id' => 3, 'product_id' => 3, 'product_name' => 'Laptop Gaming Pro 15"', 'quantity' => 8, 'date' => '2025-01-17', 'notes' => 'Pengiriman dari CV. Laptop Center'],
        ['id' => 4, 'product_id' => 4, 'product_name' => 'Laptop Ultrabook 13" I7', 'quantity' => 15, 'date' => '2025-01-18', 'notes' => 'Batch baru'],
        ['id' => 5, 'product_id' => 5, 'product_name' => 'Keyboard Mechanical RGB', 'quantity' => 30, 'date' => '2025-01-19', 'notes' => 'Stok keyboard gaming'],
        ['id' => 6, 'product_id' => 6, 'product_name' => 'Keyboard Wireless Compact', 'quantity' => 40, 'date' => '2025-01-20', 'notes' => 'Restok keyboard wireless'],
        ['id' => 7, 'product_id' => 7, 'product_name' => 'Mouse Wireless Pro', 'quantity' => 50, 'date' => '2025-01-21', 'notes' => 'Pengiriman awal bulan'],
        ['id' => 8, 'product_id' => 8, 'product_name' => 'Mouse Gaming RGB 8 Button', 'quantity' => 35, 'date' => '2025-01-22', 'notes' => 'Stock gaming mouse'],
        ['id' => 9, 'product_id' => 9, 'product_name' => 'Headset Gaming Stereo', 'quantity' => 25, 'date' => '2025-01-23', 'notes' => 'Headset gaming stock'],
        ['id' => 10, 'product_id' => 10, 'product_name' => 'Headset Wireless Premium', 'quantity' => 15, 'date' => '2025-01-24', 'notes' => 'Premium headset batch'],
        ['id' => 11, 'product_id' => 1, 'product_name' => 'Monitor LED 24" Full HD', 'quantity' => 15, 'date' => '2025-02-01', 'notes' => 'Restok monitor februari'],
        ['id' => 12, 'product_id' => 3, 'product_name' => 'Laptop Gaming Pro 15"', 'quantity' => 5, 'date' => '2025-02-03', 'notes' => 'Tambahan stok laptop gaming'],
        ['id' => 13, 'product_id' => 5, 'product_name' => 'Keyboard Mechanical RGB', 'quantity' => 20, 'date' => '2025-02-05', 'notes' => 'Restock keyboard mekanik'],
        ['id' => 14, 'product_id' => 7, 'product_name' => 'Mouse Wireless Pro', 'quantity' => 30, 'date' => '2025-02-07', 'notes' => 'Pengadaan mouse wireless'],
        ['id' => 15, 'product_id' => 2, 'product_name' => 'Monitor Curved 27" 144Hz', 'quantity' => 8, 'date' => '2025-02-10', 'notes' => 'Monitor gaming restok'],
        ['id' => 16, 'product_id' => 4, 'product_name' => 'Laptop Ultrabook 13" I7', 'quantity' => 10, 'date' => '2025-02-12', 'notes' => 'Ultrabook batch kedua'],
        ['id' => 17, 'product_id' => 6, 'product_name' => 'Keyboard Wireless Compact', 'quantity' => 25, 'date' => '2025-02-15', 'notes' => 'Keyboard wireless tambahan'],
        ['id' => 18, 'product_id' => 8, 'product_name' => 'Mouse Gaming RGB 8 Button', 'quantity' => 18, 'date' => '2025-02-17', 'notes' => 'Gaming mouse restock'],
        ['id' => 19, 'product_id' => 9, 'product_name' => 'Headset Gaming Stereo', 'quantity' => 12, 'date' => '2025-02-20', 'notes' => 'Headset gaming pengadaan'],
        ['id' => 20, 'product_id' => 10, 'product_name' => 'Headset Wireless Premium', 'quantity' => 8, 'date' => '2025-02-22', 'notes' => 'Premium headset tambahan'],
    ],

    'inventory_outs' => [
        ['id' => 1, 'product_id' => 1, 'product_name' => 'Monitor LED 24" Full HD', 'quantity' => 5, 'date' => '2025-01-25', 'description' => 'Penjualan ke perusahaan ABC'],
        ['id' => 2, 'product_id' => 3, 'product_name' => 'Laptop Gaming Pro 15"', 'quantity' => 2, 'date' => '2025-01-26', 'description' => 'Order dari toko retail'],
        ['id' => 3, 'product_id' => 5, 'product_name' => 'Keyboard Mechanical RGB', 'quantity' => 8, 'date' => '2025-01-27', 'description' => 'Penjualan online'],
        ['id' => 4, 'product_id' => 7, 'product_name' => 'Mouse Wireless Pro', 'quantity' => 12, 'date' => '2025-01-28', 'description' => 'Pengiriman ke distributor'],
        ['id' => 5, 'product_id' => 9, 'product_name' => 'Headset Gaming Stereo', 'quantity' => 6, 'date' => '2025-01-29', 'description' => 'Penjualan retail'],
    ],

    'user' => [
        'admin' => [
            'id' => 999,
            'name' => 'Demo Admin',
            'email' => 'admin@demo.com',
            'role' => 'admin',
        ],
        'staff' => [
            'id' => 998,
            'name' => 'Demo Staf',
            'email' => 'staff@demo.com',
            'role' => 'staf',
        ],
    ],
];
